# Default values for packet-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Packet API key to use, Project ID and Facility ID
secret:
  name: packet-cloud-config
  config: {}
    # apiKey: "PACKET API KEY"
    # projectID: "PACKET PROJECT ID"
    # facilityID: "PACKET FACILITY ID"
  
csi:
  driverRegistrar:
    image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
  provisioner:
    image: quay.io/k8scsi/csi-provisioner:v1.4.0
  address: /csi/csi.sock

packetDriver:
  image: docker.io/packethost/csi-packet:beb1628

# kubelet home directory
kubeletDir: /var/lib/rancher/k3s/agent/kubelet
