kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-packet-driver
  template:
    metadata:
      labels:
        app: csi-packet-driver
    spec:
      serviceAccount: csi-node-sa
      hostNetwork: true
      containers:
        - name: csi-driver-registrar
          imagePullPolicy: IfNotPresent
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=/var/lib/rancher/k3s/agent/kubelet/plugins/net.packet.csi/csi.sock"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          #  - name: registrar-socket-dir
          #    mountPath: /var/lib/csi/sockets/
        - name: packet-driver
          securityContext:
            privileged: true
          imagePullPolicy: Always
          image: docker.io/packethost/csi-packet:42377cc
          args:
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: kubelet-dir
              mountPath: /var/lib/rancher/k3s/agent/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: iscsiadm
              mountPath: /sbin/iscsiadm
            - name: plugin-dir
              mountPath: /csi
            - name: sys-devices
              mountPath: /sys/devices
            - mountPath: /dev
              name: dev
            - mountPath: /etc
              name: etc
            - mountPath: /run/udev
              name: run-udev
            - mountPath: /var/lib/iscsi
              name: var-lib-iscsi
            - name: lib-modules
              mountPath: /lib/modules
            - mountPath: /usr/share/ca-certificates/
              name: ca-certs-alternative
              readOnly: true
      volumes:
        # TODO(dependency): this will work when kublet registrar functionality exists
        #- name: registrar-socket-dir
        #  hostPath:
        #    path: /var/lib/kubelet/device-plugins/
        #    type: DirectoryOrCreate
        - name: registration-dir
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet/plugins_registry
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet/pods
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/rancher/k3s/agent/kubelet/plugins/net.packet.csi/
            type: DirectoryOrCreate
        - name: iscsiadm
          hostPath:
            path: /sbin/iscsiadm
            type: File
        - name: dev
          hostPath:
            path: /dev
            type: Directory
        - name: etc
          hostPath:
            path: /etc/
        - name: var-lib-iscsi
          hostPath:
            path: /var/lib/iscsi/
            type: DirectoryOrCreate
        - name: sys-devices
          hostPath:
            path: /sys/devices
            type: Directory
        - name: run-udev
          hostPath:
            path: /run/udev/
            type: Directory
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: Directory
        - name: ca-certs-alternative
          hostPath:
            path: /usr/share/ca-certificates/
            type: DirectoryOrCreate
