---
version: "1.0"

services:
  web:
    image: gosuri/blog
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      cpu: "100m"
      memory: "512Mi"
      disk: "1Gi"
  placement:
    attributes:
      sgx: enabled
    global:
      pricing:
        web: 200u

deployment:
  web:
    global:
      profile: web
      count: 2
